from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
from reportlab.lib.units import inch
from datetime import datetime
import io

def generate_pdf_report(data: dict) -> bytes:
    """Generate PDF report from calculation data."""
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter)
    story = []
    
    styles = getSampleStyleSheet()
    
    # Custom styles
    title_style = ParagraphStyle(
        'CustomTitle',
        parent=styles['Heading1'],
        fontSize=24,
        textColor=colors.HexColor('#2c3e50'),
        spaceAfter=30
    )
    
    heading_style = ParagraphStyle(
        'CustomHeading',
        parent=styles['Heading2'],
        fontSize=16,
        textColor=colors.HexColor('#3498db'),
        spaceAfter=12
    )
    
    normal_style = ParagraphStyle(
        'CustomNormal',
        parent=styles['Normal'],
        fontSize=12,
        textColor=colors.HexColor('#2c3e50'),
        spaceAfter=6
    )
    
    # Title
    story.append(Paragraph("ZamaniChem Engine - Calculation Report", title_style))
    story.append(Paragraph(f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", normal_style))
    story.append(Spacer(1, 20))
    
    # Add calculation results
    if 'calculation' in data:
        story.append(Paragraph("Calculation Results", heading_style))
        
        # Formula used
        if 'formula' in data:
            story.append(Paragraph(f"Formula: {data['formula']}", normal_style))
            story.append(Spacer(1, 10))
        
        # Results table
        table_data = [['Parameter', 'Value', 'Unit']]
        
        result_mapping = {
            'molarity': ('Molarity', 'M'),
            'mass_needed': ('Mass Required', 'g'),
            'concentration': ('Concentration', 'M'),
            'converted': ('Converted Value', ''),
            'c1': ('Initial Concentration', 'M'),
            'v1': ('Initial Volume', 'mL'),
            'c2': ('Final Concentration', 'M'),
            'v2': ('Final Volume', 'mL'),
            'calculated_moles': ('Calculated Moles', 'mol'),
        }
        
        for key, (label, unit) in result_mapping.items():
            if key in data and data[key]:
                value = data[key]
                if isinstance(value, (int, float)):
                    value = f"{value:.4f}"
                table_data.append([label, str(value), unit])
        
        if len(table_data) > 1:
            table = Table(table_data, colWidths=[2.5*inch, 1.5*inch, inch])
            table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#3498db')),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
                ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, 0), 12),
                ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
                ('BACKGROUND', (0, 1), (-1, -1), colors.HexColor('#f8f9fa')),
                ('GRID', (0, 0), (-1, -1), 1, colors.HexColor('#dee2e6')),
                ('FONTSIZE', (0, 1), (-1, -1), 10),
                ('PADDING', (0, 1), (-1, -1), 8),
            ]))
            story.append(table)
            story.append(Spacer(1, 20))
    
    # Add notes section
    story.append(Paragraph("Notes", heading_style))
    notes = [
        "• All calculations are performed using standard chemistry formulas",
        "• Results are rounded to 4 decimal places",
        "• For accurate laboratory work, verify calculations manually",
        "• Always follow proper safety procedures when handling chemicals",
        "• Store this report for future reference"
    ]
    
    for note in notes:
        story.append(Paragraph(note, normal_style))
        story.append(Spacer(1, 4))
    
    # Footer
    story.append(Spacer(1, 30))
    story.append(Paragraph("Generated by ZamaniChem Engine", ParagraphStyle(
        'Footer',
        parent=styles['Normal'],
        fontSize=10,
        textColor=colors.HexColor('#7f8c8d'),
        alignment=1  # Center aligned
    )))
    
    # Build PDF
    doc.build(story)
    buffer.seek(0)
    return buffer.getvalue()

def generate_quiz_pdf(quiz_results: dict) -> bytes:
    """Generate PDF report for quiz results."""
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter)
    story = []
    
    styles = getSampleStyleSheet()
    
    # Title
    story.append(Paragraph("Chemistry Quiz Results", styles['Heading1']))
    story.append(Paragraph(f"Date: {datetime.now().strftime('%Y-%m-%d')}", styles['Normal']))
    story.append(Spacer(1, 20))
    
    # Score summary
    score = quiz_results.get('score', 0)
    total = quiz_results.get('total', 0)
    percentage = quiz_results.get('percentage', 0)
    
    story.append(Paragraph(f"Score: {score}/{total} ({percentage}%)", styles['Heading2']))
    story.append(Spacer(1, 10))
    
    # Performance comment
    if percentage >= 80:
        comment = "Excellent performance! You have a strong understanding of chemistry concepts."
    elif percentage >= 60:
        comment = "Good job! You have a solid foundation in chemistry."
    else:
        comment = "Keep practicing! Review the concepts and try again."
    
    story.append(Paragraph(comment, styles['Normal']))
    story.append(Spacer(1, 20))
    
    # Question-by-question breakdown
    if 'user_answers' in quiz_results and 'questions' in quiz_results:
        story.append(Paragraph("Question Breakdown", styles['Heading2']))
        story.append(Spacer(1, 10))
        
        for i in range(len(quiz_results['questions'])):
            q = quiz_results['questions'][i]
            ua = quiz_results['user_answers'][i]
            
            status = "✓ Correct" if ua['is_correct'] else "✗ Incorrect"
            color = colors.green if ua['is_correct'] else colors.red
            
            story.append(Paragraph(f"Q{i+1}: {q['question']}", styles['Normal']))
            story.append(Paragraph(f"Your answer: {ua['user_answer']}", 
                                  ParagraphStyle('Answer', parent=styles['Normal'], textColor=color)))
            story.append(Paragraph(f"Correct answer: {ua['correct_answer']}", styles['Normal']))
            
            if not ua['is_correct'] and 'explanation' in q:
                story.append(Paragraph(f"Explanation: {q['explanation']}", 
                                      ParagraphStyle('Explanation', parent=styles['Normal'], 
                                                    fontSize=10, textColor=colors.grey)))
            
            story.append(Spacer(1, 10))
    
    # Build PDF
    doc.build(story)
    buffer.seek(0)
    return buffer.getvalue()

# Test the PDF generator
if __name__ == "__main__":
    # Test data
    test_data = {
        "calculation": "Molarity",
        "formula": "M = n / V = 0.5 mol / 0.25 L",
        "molarity": 2.0,
        "mass_needed": 29.22,
        "concentration": 0.1
    }
    
    pdf = generate_pdf_report(test_data)
    with open("test_report.pdf", "wb") as f:
        f.write(pdf)
    print("✓ PDF generated: test_report.pdf")